<?php $states = $block->getAllRegionsOfCountry();
$editRecipient = $block->getEditRecipient() ?>
<form id="pagarme-recipients-form" method="post">
    <div class="page-main-actions">
        <div class="page-actions-placeholder"></div>
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="New Recipient">
                <div class="page-actions-buttons">
                    <?php if (!$editRecipient) : ?>
                        <button id="save-button" title="Save" class="action-default primary" type="submit">
                            <span><?= __('Save') ?></span>
                        </button>
                    <?php endif; ?>
                    <button id="back" title="Back" type="button" class="action- scalable back"
                            onclick="location.href = '<?= $block->getUrl('pagarme_pagarme/recipients/index') ?>'"
                            data-ui-id="back-button">
                        <span><?= __('Back') ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Url Post-->
    <input type="hidden" id="url-post"
           value="<?= $block->getBaseUrl() . 'rest/V1/pagarme/marketplace/recipient/formData' ?>"/>
    <input type="hidden" id="url-search-recipient-id"
           value="<?= $block->getBaseUrl() . 'rest/V1/pagarme/marketplace/recipient/searchRecipient' ?>"/>

    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>"/>

    <input type="hidden" id="recipient-id-control" value=""/>

    <?php if (!empty($block->getRecipientId())) : ?>
        <!--  LocalId  -->
        <input type="hidden" name="form[id]" value="<?= $block->getLocalId() ?>">
        <!--  RecipientId  -->
        <input type="hidden" name="form[recipient_id]" value="<?= $block->getRecipientId() ?>">
    <?php endif; ?>

    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <div class="entry-edit form-inline">
                    <div class="fieldset-wrapper">
                        <div class="admin__fieldset-wrapper-content">
                            <div class="admin__fieldset">

                                <h2><?= __('Seller information') ?></h2>

                                <div class="admin__field _required" id="webkul-seller-container">
                                    <label for="webkul-seller" class="admin__field-label">
                                        <span><?= __('Select Webkul seller') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][webkul_seller]" id="webkul-seller"
                                                autofocus required>
                                            <?php if (!empty($block->getSellers())) : ?>
                                                <option value=""><?= __('Select a seller') ?></option>
                                                <?php
                                                foreach ($block->getSellers() as $seller) {
                                                    ?>
                                                    <option
                                                        data-sellername="<?php printf("%s %s", $seller['firstname'], $seller['lastname']); ?>"
                                                        data-email="<?= $seller['email'] ?>"
                                                        data-document="<?= !empty($seller['taxvat']) ? $seller['taxvat'] : '' ?>"
                                                        data-birthdate="<?= !empty($seller['dob']) ? $seller['dob'] : '' ?>"
                                                        value="<?= $seller['entity_id'] ?>">
                                                        <?php printf('%s %s (%s)', $seller['firstname'], $seller['lastname'], $seller['email']); ?>
                                                    </option>
                                                    <?php
                                                }
                                                ?>
                                            <?php endif; ?>

                                            <?php if (empty($block->getSellers())) : ?>
                                                <option value=""><?= __('No valid sellers found.') ?></option>
                                            <?php endif; ?>
                                        </select>
                                        <?php if (empty($block->getSellers())) : ?>
                                            <button type="button" class="action-basic"
                                                    onclick="location.href = '<?= $block->getUrl('customer/index/new') ?>'">
                                                <span><?= __('Create') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="seller">
                                    <label for="webkul-id" class="admin__field-label">
                                        <span><?= __('Webkul ID') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][external_id]" id="webkul-id" readonly
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" id="use_existing_pagarme_id" data-section="seller">
                                    <label for="existing_recipient" class="admin__field-label">
                                        <span><?= __('Use an existing Pagar.me recipient') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[existing_recipient]"
                                                id="existing_recipient" data-toggle-required>
                                            <option value="0"><?= __('No') ?></option>
                                            <option value="1"><?= __('Yes') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required" id="pagarme_id" data-section="pagarme_id">
                                    <label for="recipient-id" class="admin__field-label">
                                        <span><?= __('ID Pagar.me') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[pagarme_id]" id="recipient-id" data-toggle-required>
                                        <button type="button" class="action-basic" id="search-recipient-id"
                                                data-action="">
                                            <span><?= __('Get info') ?></span>
                                        </button>
                                        <p id="error-message" class="error-message"></p>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="seller">
                                    <label for="document-type" class="admin__field-label">
                                        <span><?= __('Document type') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][type]" id="document-type"
                                                data-document-type-for="seller" data-toggle-required>
                                            <option value=""><?= __('Select') ?></option>
                                            <option value="individual"><?= __('CPF') ?></option>
                                            <option value="corporation"><?= __('CNPJ') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <h2 data-section="individual"><?= __('Personal data') ?></h2>
                                <h2 data-section="corporation"><?= __('Company data') ?></h2>

                                <div class="admin__field _required" data-section="individual corporation">
                                    <label for="document" class="admin__field-label">
                                        <span><?= __('Document number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][document]" id="document"
                                               placeholder="000.000.000-00" maxlength="14"
                                               data-document-number-for="seller"
                                               data-document-mask data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="individual">
                                    <label for="recipient-name" class="admin__field-label">
                                        <span><?= __('Name') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][name]" id="recipient-name"
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="corporation">
                                    <label for="recipient-company-name" class="admin__field-label">
                                        <span><?= __('Company name') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][company_name]"
                                               id="recipient-company-name"
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="corporation">
                                    <label for="recipient-trading-name" class="admin__field-label">
                                        <span><?= __('Trading name') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][trading_name]"
                                               id="recipient-trading-name"
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="individual corporation">
                                    <label for="recipient-email" class="admin__field-label">
                                        <span><?= __('E-mail') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="email" class="recipient-form-inputs"
                                               name="form[register_information][email]" id="recipient-email"
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field" data-section="individual corporation new-field">
                                    <label for="recipient-site" class="admin__field-label">
                                        <span><?= __('Site URL') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="url" class="recipient-form-inputs"
                                               name="form[register_information][site_url]" id="recipient-site">
                                    </div>
                                </div>

                                <div class="admin__field" data-section="individual new-field">
                                    <label for="recipient-mother-name" class="admin__field-label">
                                        <span><?= __('Mother name') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][mother_name]"
                                               id="recipient-mother-name">
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="individual new-field">
                                    <label for="recipient-birthdate" class="admin__field-label">
                                        <span><?= __('Date of birth') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][birthdate]" id="recipient-birthdate"
                                               placeholder="dd/mm/yyyy" data-datepicker data-date-mask
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="individual new-field">
                                    <label for="recipient-monthly-income" class="admin__field-label">
                                        <span><?= __('Monthly income') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][monthly_income]"
                                               id="recipient-monthly-income" placeholder="00.000,00" data-currency-mask
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="individual new-field">
                                    <label for="recipient-professional-occupation" class="admin__field-label">
                                        <span><?= __('Profession') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][professional_occupation]"
                                               id="recipient-professional-occupation" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="corporation new-field">
                                    <label for="recipient-annual-revenue" class="admin__field-label">
                                        <span><?= __('Annual revenue') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][annual_revenue]"
                                               id="recipient-annual-revenue" placeholder="0.000.000,00"
                                               data-currency-mask data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field" data-section="corporation new-field">
                                    <label for="recipient-corporation-type" class="admin__field-label">
                                        <span><?= __('Company type') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][corporation_type]"
                                               id="recipient-corporation-type">
                                    </div>
                                </div>

                                <div class="admin__field" data-section="corporation new-field">
                                    <label for="recipient-founding-date" class="admin__field-label">
                                        <span><?= __('Founding date') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][founding_date]"
                                               id="recipient-founding-date"
                                               placeholder="dd/mm/yyyy" data-datepicker data-date-mask>
                                    </div>
                                </div>

                            </div>
                            <div class="admin__fieldset" data-section="individual corporation new-field">

                                <div class="admin__field">
                                    <div class="admin__field-label">
                                        <h3><?= __('Phone numbers') ?></h3>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-phones-type-0" class="admin__field-label">
                                        <span><?= __('Contact type') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][phone_number][0][type]"
                                                id="recipient-phones-type-0" data-toggle-required>
                                            <option value="mobile_phone"><?= __('Mobile phone') ?></option>
                                            <option value="home_phone"><?= __('Telephone') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-phones-number-0" class="admin__field-label">
                                        <span><?= __('Contact number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="tel" class="recipient-form-inputs"
                                               name="form[register_information][phone_number][0][number]"
                                               id="recipient-phones-number-0" placeholder="(00) 00000-0000"
                                               data-phone-mask data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-phones-type-1" class="admin__field-label">
                                        <span><?= __('Contact type') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][phone_number][1][type]"
                                                id="recipient-phones-type-1">
                                            <option value="mobile_phone"><?= __('Mobile phone') ?></option>
                                            <option value="home_phone"><?= __('Telephone') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-phones-number-1" class="admin__field-label">
                                        <span><?= __('Contact number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="tel" class="recipient-form-inputs"
                                               name="form[register_information][phone_number][1][number]"
                                               id="recipient-phones-number-1" placeholder="(00) 00000-0000"
                                               data-phone-mask>
                                    </div>
                                </div>

                            </div>
                            <div class="admin__fieldset" data-section="individual new-field">

                                <div class="admin__field">
                                    <div class="admin__field-label">
                                        <h3><?= __('Address') ?></h3>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-zip-code" class="admin__field-label">
                                        <span><?= __('Zip/Postal Code') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][address][zip_code]"
                                               id="recipient-zip-code"
                                               placeholder="00000-000" data-zipcode-mask data-cep-search
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-street" class="admin__field-label">
                                        <span><?= __('Street') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][address][street]" id="recipient-street"
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-street-number" class="admin__field-label">
                                        <span><?= __('Number') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][address][street_number]"
                                               id="recipient-street-number" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-complementary" class="admin__field-label">
                                        <span><?= __('Complement') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][address][complementary]"
                                               id="recipient-complementary">
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-reference-point" class="admin__field-label">
                                        <span><?= __('Reference point') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][address][reference_point]"
                                               id="recipient-reference-point">
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-neighborhood" class="admin__field-label">
                                        <span><?= __('Neighborhood') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][address][neighborhood]"
                                               id="recipient-neighborhood" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-state" class="admin__field-label">
                                        <span><?= __('State/Province') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][address][state]" id="recipient-state"
                                                data-state
                                                data-toggle-required>
                                            <option value=""><?= __('Select') ?></option>
                                            <?php foreach ($states as $state) {
                                                echo "<option value='{$state['code']}'>{$state['default_name']}</option>";
                                            } ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-city" class="admin__field-label">
                                        <span><?= __('City') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" list="recipient-cities" class="recipient-form-inputs"
                                               name="form[register_information][address][city]" id="recipient-city"
                                               data-toggle-required>
                                        <datalist id="recipient-cities"></datalist>
                                    </div>
                                </div>

                            </div>
                            <div class="admin__fieldset" data-section="corporation new-field">

                                <div class="admin__field">
                                    <div class="admin__field-label">
                                        <h3><?= __('Company address') ?></h3>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="company-zip-code" class="admin__field-label">
                                        <span><?= __('Zip/Postal Code') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][main_address][zip_code]"
                                               id="company-zip-code" placeholder="00000-000" data-zipcode-mask
                                               data-cep-search data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="company-street" class="admin__field-label">
                                        <span><?= __('Street') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][main_address][street]"
                                               id="company-street"
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="company-street-number" class="admin__field-label">
                                        <span><?= __('Number') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][main_address][street_number]"
                                               id="company-street-number" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="company-complementary" class="admin__field-label">
                                        <span><?= __('Complement') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][main_address][complementary]"
                                               id="company-complementary">
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="company-reference-point" class="admin__field-label">
                                        <span><?= __('Reference point') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][main_address][reference_point]"
                                               id="company-reference-point">
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="company-neighborhood" class="admin__field-label">
                                        <span><?= __('Neighborhood') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][main_address][neighborhood]"
                                               id="company-neighborhood" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="company-state" class="admin__field-label">
                                        <span><?= __('State/Province') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][main_address][state]"
                                                id="company-state"
                                                data-state
                                                data-toggle-required>
                                            <option value=""><?= __('Select') ?></option>
                                            <?php foreach ($states as $state) {
                                                echo "<option value='{$state['code']}'>{$state['default_name']}</option>";
                                            } ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="company-city" class="admin__field-label">
                                        <span><?= __('City') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" list="company-cities" class="recipient-form-inputs"
                                               name="form[register_information][main_address][city]" id="company-city"
                                               data-toggle-required>
                                        <datalist id="company-cities"></datalist>
                                    </div>
                                </div>

                            </div>
                            <div class="admin__fieldset" data-section="corporation new-field">

                                <div class="admin__field">
                                    <div class="admin__field-label">
                                        <h3><?= __('Managing partner') ?></h3>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-name" class="admin__field-label">
                                        <span><?= __('Name') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" list="recipient-partner-0-partners-list"
                                               class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][name]"
                                               id="recipient-partner-0-name" data-toggle-required>
                                        <datalist id="recipient-partner-0-partners-list"></datalist>
                                    </div>
                                </div>

                                <input type="hidden" name="form[register_information][managing_partners][0][type]"
                                       id="recipient-partner-document-type-0"
                                       value="individual" data-toggle-required>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-document" class="admin__field-label">
                                        <span><?= __('Document number') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][document]"
                                               id="recipient-partner-0-document" placeholder="000.000.000-00"
                                               maxlength="14" data-document-mask data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-partner-0-mother-name" class="admin__field-label">
                                        <span><?= __('Mother name') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][mother_name]"
                                               id="recipient-partner-0-mother-name">
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-email" class="admin__field-label">
                                        <span><?= __('E-mail') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="email" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][email]"
                                               id="recipient-partner-0-email" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-birthdate" class="admin__field-label">
                                        <span><?= __('Date of birth') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][birthdate]"
                                               id="recipient-partner-0-birthdate" placeholder="dd/mm/yyyy"
                                               data-datepicker data-date-mask data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-monthly-income" class="admin__field-label">
                                        <span><?= __('Monthly income') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][monthly_income]"
                                               id="recipient-partner-0-monthly-income" placeholder="0.000,00"
                                               data-currency-mask data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-professional-occupation"
                                           class="admin__field-label">
                                        <span><?= __('Profession') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][professional_occupation]"
                                               id="recipient-partner-0-professional-occupation" data-toggle-required>
                                    </div>
                                </div>

                                <input type="hidden"
                                       name="form[register_information][managing_partners][0][self_declared_legal_representative]"
                                       id="recipient-partner-0-declaration"
                                       value="1" data-toggle-required>

                            </div>
                            <div class="admin__fieldset" data-section="corporation new-field">

                                <div class="admin__field">
                                    <div class="admin__field-label">
                                        <h3><?= __('Managing partner phone numbers') ?></h3>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-phones-type-0" class="admin__field-label">
                                        <span><?= __('Contact type') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][managing_partners][0][phone_number][0][type]"
                                                id="recipient-partner-0-phones-type-0" data-toggle-required>
                                            <option value="mobile_phone"><?= __('Mobile phone') ?></option>
                                            <option value="home_phone"><?= __('Telephone') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-phones-number-0" class="admin__field-label">
                                        <span><?= __('Contact number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="tel" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][phone_number][0][number]"
                                               id="recipient-partner-0-phones-number-0" placeholder="(00) 00000-0000"
                                               data-phone-mask data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-partner-0-phones-type-1" class="admin__field-label">
                                        <span><?= __('Contact type') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][managing_partners][0][phone_number][1][type]"
                                                id="recipient-partner-0-phones-type-1">
                                            <option value="mobile_phone"><?= __('Mobile phone') ?></option>
                                            <option value="home_phone"><?= __('Telephone') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-partner-0-phones-number-1" class="admin__field-label">
                                        <span><?= __('Contact number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="tel" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][phone_number][1][number]"
                                               id="recipient-partner-0-phones-number-1" placeholder="(00) 00000-0000"
                                               data-phone-mask>
                                    </div>
                                </div>

                            </div>
                            <div class="admin__fieldset" data-section="corporation new-field">

                                <div class="admin__field">
                                    <div class="admin__field-label">
                                        <h3><?= __('Managing partner address') ?></h3>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-zip-code" class="admin__field-label">
                                        <span><?= __('Zip/Postal Code') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][address][zip_code]"
                                               id="recipient-partner-0-zip-code" placeholder="00000-000"
                                               data-zipcode-mask data-cep-search data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-street" class="admin__field-label">
                                        <span><?= __('Street') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][address][street]"
                                               id="recipient-partner-0-street" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-street-number" class="admin__field-label">
                                        <span><?= __('Number') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][address][street_number]"
                                               id="recipient-partner-0-street-number" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-partner-0-complementary" class="admin__field-label">
                                        <span><?= __('Complement') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][address][complementary]"
                                               id="recipient-partner-0-complementary">
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="recipient-partner-0-reference-point" class="admin__field-label">
                                        <span><?= __('Reference point') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][address][reference_point]"
                                               id="recipient-partner-0-reference-point">
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-neighborhood" class="admin__field-label">
                                        <span><?= __('Neighborhood') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][address][neighborhood]"
                                               id="recipient-partner-0-neighborhood" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-state" class="admin__field-label">
                                        <span><?= __('State/Province') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[register_information][managing_partners][0][address][state]"
                                                id="recipient-partner-0-state"
                                                data-state
                                                data-toggle-required>
                                            <option value=""><?= __('Select') ?></option>
                                            <?php foreach ($states as $state) {
                                                echo "<option value='{$state['code']}'>{$state['default_name']}</option>";
                                            } ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="recipient-partner-0-city" class="admin__field-label">
                                        <span><?= __('City') ?></span>
                                    </label>
                                    <div class="admin__field-control ">
                                        <input type="text" list="recipient-partner-0-cities"
                                               class="recipient-form-inputs"
                                               name="form[register_information][managing_partners][0][address][city]"
                                               id="recipient-partner-0-city"
                                               data-toggle-required>
                                        <datalist id="recipient-partner-0-cities"></datalist>
                                    </div>
                                </div>

                            </div>
                            <div class="admin__fieldset" data-section="individual corporation">

                                <h2><?= __('Banking information') ?></h2>

                                <p class="recipient-block-info"><?= __('The bank account holder must be the recipient (same document number).') ?></p>

                                <div class="admin__field _required">
                                    <label for="holder-name" class="admin__field-label">
                                        <span><?= __('Holder name') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[holder_name]" id="holder-name"
                                               readonly data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="holder-document-type" class="admin__field-label">
                                        <span><?= __('Document type') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[holder_document_type]"
                                                id="holder-document-type" readonly data-toggle-required>
                                            <option value=""><?= __('Select') ?></option>
                                            <option value="individual"><?= __('CPF') ?></option>
                                            <option value="company"><?= __('CNPJ') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="holder-document" class="admin__field-label">
                                        <span><?= __('Document number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[holder_document]" id="holder-document"
                                               placeholder="000.000.000-00" maxlength="14" readonly data-document-mask
                                               data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="bank" class="admin__field-label">
                                        <span><?= __('Bank code') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs" maxlength="3"
                                               name="form[bank]" id="bank" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="branch-number" class="admin__field-label">
                                        <span><?= __('Branch number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs" maxlength="5"
                                               pattern="[0-9]{0,5}" name="form[branch_number]"
                                               id="branch-number" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label for="branch-check-digit" class="admin__field-label">
                                        <span><?= __('Branch check digit') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs"
                                               name="form[branch_check_digit]" id="branch-check-digit">
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="account-number" class="admin__field-label">
                                        <span><?= __('Account number') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs" maxlength="13"
                                               pattern="[0-9]{0,13}" name="form[account_number]"
                                               id="account-number" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="account-check-digit" class="admin__field-label">
                                        <span><?= __('Account check digit') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input type="text" class="recipient-form-inputs" maxlength="2"
                                               name="form[account_check_digit]"
                                               id="account-check-digit" data-toggle-required>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label for="account-type" class="admin__field-label">
                                        <span><?= __('Account type') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[account_type]" id="account-type">
                                            <option value="checking"><?= __('Checking') ?></option>
                                            <option value="savings"><?= __('Savings') ?></option>
                                            <option value="conjunct_checking"><?= __('Conjunct checking') ?></option>
                                            <option value="conjunct_savings"><?= __('Conjunct savings') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <h2><?= __('Transfer settings') ?></h2>

                                <div class="admin__field">
                                    <label for="transfer-enabled" class="admin__field-label">
                                        <span><?= __('Enable automatic transfer') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[transfer_enabled]" id="transfer-enabled">
                                            <option value="0"><?= __('No') ?></option>
                                            <option value="1"><?= __('Yes') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="transfer_interval"
                                     id="transfer-interval-div">
                                    <label for="transfer-interval" class="admin__field-label">
                                        <span><?= __('Transfer interval') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[transfer_interval]" id="transfer-interval"
                                                data-toggle-required>
                                            <option value="Daily"><?= __('Daily') ?></option>
                                            <option value="Weekly"><?= __('Weekly') ?></option>
                                            <option value="Monthly"><?= __('Monthly') ?></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field _required" data-section="transfer_day" id="transfer-day-div">
                                    <label for="transfer-day" class="admin__field-label">
                                        <span><?= __('Transfer day') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="recipient-form-inputs admin__control-select"
                                                name="form[transfer_day]" id="transfer-day" data-toggle-required>
                                            <option value="0">0</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- Edit Recipient-->
<input type="hidden" name="form[edit_recipient_id]" id="edit-recipient" value='<?= $editRecipient ?>'/>
