---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MAGENTO 2
  title: MAGENTO 2
  description: Módulo fechado para integração com o sistema de e-commerce Magento versão 2 para a P&G
  namespace: pagarme-psp
  annotations:
    legacy.stone.tech/owner-email: CHANGE_ME
    legacy.stone.tech/prod-date: CHANGE_ME
    stone.tech/on-prem-sites: *
  labels:
    legacy.stone.tech/internal-user-auth-base: CHANGE_ME
    legacy.stone.tech/access-request-type:  CHANGE_ME
    legacy.stone.tech/handle-lgpd:  CHANGE_ME
    legacy.stone.tech/customer-auth-method:  CHANGE_ME
    stone.tech/endpoint-type:  CHANGE_ME
spec:
  type: service
  lifecycle: production
  owner: pagarme/ADD_OWNER_TEAM #CHANGE IF NOT OWNER TEAM IS CORRECTLY
