<?php
/**
 * var Pagarme\Pagarme\Block\Payment\Info\Billet $this
 *
 * @author      Open Source Team
 * @copyright   2021 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */
?>

<?php if ($this->getInfo()->getOrder()->getStatus() == 'pending'): ?>
    <p><?php echo __($this->getTitle()) ?></p>
    <hr />
    <p><a class="action tocart primary" id="pagarme-link-boleto" href="<?php echo $this->getBilletUrl() ?>" target="_blank"><?php echo __('Print Billet') ?></a></p>
<?php else: ?>
	<p><?php echo __($this->getTitle()) ?></p>
<?php endif ?>
