<?php
    /**
     * @var \Pagarme\Core\Kernel\Aggregates\Transaction $info
     */
    $info =  $this->getTransactionInfo();
?>
<?php if ($this->getCcType()) : ?>
    <span>
        <?= __($this->getTitle()); ?>
    </span>
    <br /><br />
    <span>
        <b><?= __('Brand'); ?>: </b>
        <?= $info['cardBrand'] ?>
    </span><br />
    <span>
        <b><?= __('Number'); ?>: </b>
        <?= sprintf("**** **** **** %s", $info['lastFour']); ?>
    </span>
    <br />
    <span>
        <b><?= __('Installments'); ?>: </b>
        <?= $info['installments'] ?>
    </span>
<?php endif ?>