<?php
/**
 * var Pagarme\Pagarme\Block\Payment\Info\CreditCard $this
 *
 * @author      Open Source Team
 * @copyright   2021 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

?>
<p><?= __($this->getTitle()); ?></p>
<p>
    <b><?= __('Brand'); ?>:</b> <?= ucfirst($this->getCcBrand()); ?><br/>
    <b><?= __('Number'); ?>:</b> <?= $this->getCardLast4(); ?><br/>
    <b><?= __('Installments'); ?>:</b> <?= $this->getInstallments(); ?>
</p>
