<?php
/**
 * @var $block \Pagarme\Pagarme\Block\Adminhtml\Order\Charge\Tab\View
 */
?>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= __('Charges') ?></span>
    </div>
    <table class="admin__table-secondary">
        <thead>
            <th><?= __('Charge ID') ?></th>
            <th><?= __('Amount') ?></th>
            <th><?= __('Paid Amount') ?></th>
            <th><?= __('Canceled Amount') ?></th>
            <th><?= __('Refunded Amount') ?></th>
            <th><?= __('Status') ?></th>
            <th></th>
            <th></th>
            <th></th>
        </thead>
        <tbody>
            <?= $block->getChargesTableBody() ?>
        </tbody>
    </table>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "orderCharge": {
                "urlCancel": "<?= $block->getChargeCancelUrl();?>",
                "urlCapture": "<?= $block->getChargeCaptureUrl();?>"
            }
        }
    }
</script>
