<?php
/**
 * Phtml List Cards
 *
 * @author      MundiPagg Embeddables Team <embeddables@mundipagg.com>
 * @copyright   2017 MundiPagg (http://www.mundipagg.com)
 * @license     http://www.mundipagg.com Copyright
 *
 * @link        http://www.mundipagg.com
 */

$i = 0;
?>

<div>
	<table class="table">

		<thead>
		  <tr>
		    <th><?php echo __('Id') ?></th>
		    <th><?php echo __('Credit Card') ?></th>
		    <th><?php echo __('Brand') ?></th>
		    <th><?php echo __('Created At') ?></th>
		    <th><?php echo __('Remove') ?></th>
		  </tr>
		</thead>

		<tbody>
			<?php foreach ($block->getCardsList() as $item): ?>
				<?php $i++; ?>
				<?php $url = $this->getBaseUrl() . 'mundipagg/customer/remove/id/'. $item->getId() ?>
				<tr>
					<td><?php echo $i ?></td>
					<td><?php echo $item->getMaskedNumber() ?></td>
					<td><?php echo $item->getBrand() ?></td>
					<td><?php echo $item->getCreatedAt() ?></td>
					<td><button onclick="location.href = '<?php echo $url ?>';" id="remove"><?php echo __('Remove') ?></button></td>
				</tr>
			
			<?php endforeach; ?>
		</tbody>
	</table>
</div>