<?php
/**
 * Phtml List Cards
 *
 * @author      Open Source Team
 * @copyright   2021 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

$i = 0;
?>

<div>
	<table class="table">

		<thead>
		  <tr>
		    <th><?php echo __('Id') ?></th>
		    <th><?php echo __('Credit Card') ?></th>
		    <th><?php echo __('Brand') ?></th>
		    <th><?php echo __('Created At') ?></th>
		    <th><?php echo __('Remove') ?></th>
		  </tr>
		</thead>

		<tbody>
			<?php foreach ($block->getCardsList() as $item): ?>
				<?php $i++; ?>
				<?php $url = $this->getBaseUrl() . 'pagarme/customer/remove/id/'. $item->getId() ?>
				<tr>
					<td><?php echo $i ?></td>
					<td><?php echo $item->getMaskedNumber() ?></td>
					<td><?php echo $item->getBrand() ?></td>
					<td><?php echo $item->getCreatedAt() ?></td>
					<td><button onclick="location.href = '<?php echo $url ?>';" id="remove"><?php echo __('Remove') ?></button></td>
				</tr>

			<?php endforeach; ?>
		</tbody>
	</table>
</div>
