<?php
/**
 * @var \Pagarme\Pagarme\Block\Customer\Invoice $block
 */
?>
<div>
    <table class="table">

        <thead>
            <tr>
                <th><?= __('Id') ?></th>
                <th><?= __('Amount') ?></th>
                <th><?= __('Paid amount') ?></th>
                <th><?= __('Canceled amount') ?></th>
                <th><?= __('Refunded amount') ?></th>
                <th><?= __('Status') ?></th>
                <th><?= __('Payement method') ?></th>
                <?= $block->getBoletoHeader() ?>
            </tr>
        </thead>
        <tbody>
            <?= $block->getInvoicesTableBody() ?>
        </tbody>
    </table>
</div>
