<?php
/**
 * Phtml List Subscription
 *
 * @author      MundiPagg Embeddables Team <embeddables@mundipagg.com>
 * @copyright   2019 MundiPagg (http://www.mundipagg.com)
 * @license     http://www.mundipagg.com Copyright
 *
 * @link        http://www.mundipagg.com
 */

$i = 0;
/* @var \MundiPagg\MundiPagg\Block\Customer\Subscription $block */
?>
<div>
    <table class="table">

        <thead>
        <tr>
            <th><?= __('Id') ?></th>
            <th><?= __('Order Recurrence') ?></th>
            <th><?= __('Status') ?></th>
            <th><?= __('Installments') ?></th>
            <th><?= __('Type recurrence') ?></th>
            <th><?= __('Type interval') ?></th>
            <th><?= __('Count Interval') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getAllSubscriptionRecurrenceCoreByCustomerId() as $item) : ?>
            <?php $i++; ?>
            <?php
                $url = $this->getBaseUrl() . 'mundipagg/customer/invoice/?code='. $item->getMundipaggId()->getValue();
                $status = $item->getStatus()->getStatus();
                $recurrenceType = $item->getRecurrenceType();
                $intervalType = $item->getIntervalType();
            ?>
            <tr>
                <td><?= $i ?></td>
                <td><?= $item->getCode() ?></td>
                <td><?= __($status) ?></td>
                <td><?= $item->getInstallments() ?></td>
                <td><?= __($recurrenceType) ?></td>
                <td><?= __($intervalType) ?></td>
                <td><?= $item->getIntervalCount() ?></td>
                <td>
                    <button onclick="location.href = '<?= $url ?>';" id="details">
                        <?= __("View Details") ?>
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>