<?php
    $pixInfo =  $this->getPixInfo();
    if (!empty($pixInfo)):
?>
    <hr />
    <div style="text-align: center">
        <div style="margin-bottom: 40px">
            <img width="200" src="https://staging-cdn.mundipagg.com/assets/images/site/illustrations/pix-bc-logo-2.png" />
        </div>
        <div style="margin-bottom: 20px">
            <img width="200" src="<?= $pixInfo['qr_code_url']?>" />
        </div>
        <a style="cursor: pointer" onclick="copyQrCode()">Copiar Código do Pix</a>
        <input style="display: none;" type="text" value="<?= $pixInfo['qr_code']?>" id="mp_qr_code" />
    </div>

    <script>
        function copyQrCode() {
            var copyText = document.getElementById("mp_qr_code");

            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");

            alert("Codigo Pix copiado");
        }
    </script>
<?php endif ?>