<?php
/**
 * @var \Pagarme\Pagarme\Block\Payment\Tds  $this
 */
    if(!$this->canInitTds()) {
        return;
    }
?>
<!-- NX/Auth Switch containers -->
<div id="tdsMethodContainer" style="display: none;"></div>
<div id="challengeContainer" class="stoneChallengeIframeElement"></div>

<!-- Stone NX 3DS SDK -->
<script src="<?= $this->getNxSdkUrl(); ?>"></script>
<script src="<?= $this->getTifaSdkUrl(); ?>"></script>
