<?php
/**
 * @var \Pagarme\Pagarme\Block\Payment\Tds  $this
 */
    if(!$this->canInitTds()) {
        return;
    }
?>
<div id="challengeIframeElement" class="challengeIframeElement">
    <div class="modal-content">
    <iframe
        name="challengeIframe"
        id="challengeIframe"
        frameborder="0"
        style="width: 500px; height: 600px"
    ></iframe>
    </div>
</div>
<script src="<?= $this->getSdkUrl(); ?>"></script>
<style>
    .challengeIframeElement {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0, 0, 0);
        background-color: rgba(0, 0, 0, 0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 20px;
        border: 1px solid #888;
        max-width: fit-content;
    }

    #challengeIframe {
        display: none;
    }
</style>
