<?php
$cicleSelectOption = $this->getCicleSelectOption();
$quantityOptionCicle = 4;
?>

<form id="form-product" method="post">
    <div class="page-main-actions">
        <div class="page-actions-placeholder"></div>
        <div class="page-actions"
             data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="New Subscription">
                <div class="page-actions-buttons">
                    <button title="Save" class="action-default primary" id="save-button" type="submit">
                        <span><?php echo __('Save') ?></span>
                    </button>
                    <button id="back" title="Back" type="button"
                            class="action- scalable back"
                            onclick="location.href = '<?php echo $block->getUrl('pagarme_pagarme/recurrenceproducts/index') ?>'"
                            data-ui-id="back-button">
                        <span><?php echo __('Back') ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Bundle Products-->
    <input id="products-bundle" value='<?php echo $block->getBundleProducts(); ?>' type="hidden"/>

    <!-- Edit Product-->
    <input id="edit-product" name='form[edit_product_id]' value='<?php echo $block->getEditProduct(); ?>' type="hidden"/>

    <!-- Product Id-->
    <input id="product-recurrence-id" name='form[id]' value='<?php echo $block->getProductId(); ?>' type="hidden"/>

    <!-- Recurrence Type-->
    <input id="recurrence-type" name='' value='<?php echo $block->getRecurrenceType(); ?>' type="hidden"/>

    <!-- Url Search-->
    <input id="url-search" value="<?php echo $block->getUrl('*/plans/searchproduct'); ?>" type="hidden"/>

    <!-- Url Post-->
    <input id="url-post" value="<?php echo $block->getBaseUrl() . 'rest/V1/pagarme/recurrence/product/formData'; ?>" type="hidden"/>

    <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />

    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <div class="entry-edit form-inline">
                    <div class="fieldset-wrapper">
                        <div class="admin__fieldset-wrapper-content _hide">
                            <fieldset class="admin__fieldset">

                                <div class="fieldset-wrapper admin__collapsible-block-wrapper products-wrapper" data-role="collapsible">
                                    <h1><?php echo __('Products') ?></h1>
                                    <div class="select-product">
                                        <h2><?php echo __('Add a product') ?></h2>
                                        <label><?php echo __('Product Search') ?></label>
                                        <input type="text" class="product_search" name="product_search" id="product-search">
                                        <input type="hidden" id="product_id" name="form[product_id]">
                                        <input type="hidden" id="product_name" name="form[name]">
                                        <input type="hidden" id="product_image">
                                        <button type="button" class="action-basic" id="add-product" data-action="add">
                                            <span><?php echo __('Add Product') ?></span>
                                        </button>
                                        <p id="error-message" class="error-message"></p>
                                    </div>

                                    <div class="admin__control-table-wrapper table-products" id="table-products">
                                        <div id="info-bundle" class="info-bundle">
                                            <div class="info-bundle-header">
                                                <strong><span></span></strong>
                                            </div>
                                        </div>
                                        <table id="product-info" class="admin__dynamic-rows admin__control-table">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th><?php echo __('Name') ?></th>
                                                    <th><?php echo __('Original Price') ?></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label class="admin__field-label">
                                        <span><?php echo __('Payment Methods') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <div class="admin__field admin__field-option">
                                            <input type="checkbox" class="admin__control-checkbox" name="form[credit_card]" id="credit-card" >
                                            <label class="admin__field-label" for="credit-card"><?php echo __('Credit Card') ?></label>
                                        </div>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label class="admin__field-label">
                                        <span> </span>
                                    </label>
                                    <div class="admin__field-control">
                                        <div class="admin__field admin__field-option">
                                            <input type="checkbox" class="admin__control-checkbox" name="form[boleto]" id="boleto" >
                                            <label class="admin__field-label" for="boleto"><?php echo __('Boleto') ?></label>
                                        </div>
                                    </div>
                                </div>

                                <div class="admin__field" id="allow_installments_div">
                                    <label class="admin__field-label">
                                        <span><?php echo __('Allow Installments') ?></span>
                                    </label>
                                    <div class="admin__field-control _with-tooltip">
                                        <div class="admin__field admin__field-option">
                                            <input type="checkbox" class="admin__control-checkbox" name="form[allow_installments]" id="allow_installments" >
                                            <label class="admin__field-label" for="allow_installments"></label>
                                        </div>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label class="admin__field-label">
                                        <span><?php echo __('Allow sell as normal product') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <div class="admin__field admin__field-option">
                                            <input type="checkbox" class="admin__control-checkbox" name="form[sell_as_normal_product]" id="sell_as_normal_product" >
                                            <label class="admin__field-label" for="sell_as_normal_product"></label>
                                        </div>
                                    </div>
                                </div>

                                <div class="admin__field _required">
                                    <label class="admin__field-label" for="enable">
                                        <span><?php echo __('Repetitions') ?></span>
                                    </label>
                                    <div class="admin__field-control">
                                        <table class="table-cycles">
                                            <tr>
                                                <th><?php echo __('Interval') ?></th>
                                                <th><?php echo __('Type') ?></th>
                                                <th><?php echo __('Recurrence price') ?></th>
                                                <th><?php echo __('Cycles') ?></th>
                                            </tr>
                                            <?php for ($i = 1; $i <= $quantityOptionCicle; $i++) : ?>
                                                <tr>
                                                    <td>
                                                        <select class="admin__control-select" name="form[repetitions][<?php echo $i ?>][interval_count]" id="interval_count_<?php echo $i ?>">
                                                            <option value="">Select Interval</option>
                                                            <?php foreach ($cicleSelectOption['interval_count'] as $interval) : ?>
                                                                <option><?= $interval ?></option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    </td>
                                                    <td>
                                                        <select class="admin__control-select" name="form[repetitions][<?php echo $i ?>][interval]" id="interval_<?php echo $i ?>">
                                                            <option value="">Select Type</option>
                                                            <?php foreach ($cicleSelectOption['interval_type'] as $key => $intervalType) : ?>
                                                                <option value="<?= $key ?>"><?= $intervalType ?></option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    </td>
                                                    <td>
                                                        <input type="text" class="recurrence_price ui-autocomplete-input" name="form[repetitions][<?php echo $i ?>][recurrence_price]" id="recurrence_price_<?php echo $i ?>" value="0,00">
                                                    </td>

                                                    <td>
                                                        <input type="text" class="cycles ui-autocomplete-input" name="form[repetitions][<?php echo $i ?>][cycles]" id="cycles_<?php echo $i ?>" value="0">
                                                    </td>
                                                    <input type="hidden" id="repetition_id_<?php echo $i ?>" name="form[repetitions][<?php echo $i ?>][id]"/>
                                                </tr>
                                            <?php endfor; ?>
                                        </table>
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
