<?php $subscription = $this->getSubscriptionDetails(); ?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Subscription data') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Order') ?> # <?= $subscription->getCode(); ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                        <tr>
                            <th><?= __('Subscription created at') ?></th>
                            <td><?= $subscription->getCreatedAt(); ?></td>
                        </tr>
                        <?php if ( $subscription->getStatus() === $this->getDisabledStatusName()) { ?>
                            <tr>
                                <th><?= __('Subscription disabled at') ?></th>
                                <td><?= $subscription->getUpdatedAt(); ?></td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <th><?= __('Subscription status') ?></th>
                            <td>
                                <span id="order_status">
                                    <?= $subscription->getPlatformOrder()->getStatus(); ?>
                                    (<?= $subscription->getPlatformOrder()->getState()->getState(); ?>)
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= __('Payment method') ?></th>
                            <td><span><?= $subscription->getPaymentMethod(); ?></span></td>
                        </tr>

                        <tr>
                            <th><?= __('Interval') ?></th>
                            <td><span><?= $subscription->getIntervalType(); ?></span></td>
                        </tr>
                        <tr>
                            <th><?= __('Total cycle counting of a product') ?></th>
                            <td><span>!!!</span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title"><?= __('Customer information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tbody>
                        <tr>
                            <th><?= __('Customer id') ?></th>
                            <td>
                                <span><?= $subscription->getPlatformOrder()->getCustomer()->getMundiPaggId()->getValue(); ?></span>
                            </td>
                        </tr><tr>
                            <th><?= __('Customer name') ?></th>
                            <td>
                                <span><?= $subscription->getPlatformOrder()->getCustomer()->getName(); ?></span>
                            </td>
                        </tr>
                        <tr>
                            <th>E-mail</th>
                            <td><?= $subscription->getPlatformOrder()->getCustomer()->getEmail(); ?></td>
                        </tr>
                        <tr>
                            <th><?= __('Document') ?></th>
                            <td><?= $subscription->getPlatformOrder()->getCustomer()->getDocument() ;?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Items Ordered') ?></span>
    </div>
    <table class="data-grid" data-role="grid">
        <thead>
        <tr>
            <th class="data-grid-th">
                <span class="data-grid-cell-content">ID</span>
            </th>
            <th class="data-grid-th">
                <span class="data-grid-cell-content"><?= __('Product Name') ?></span>
            </th>
            <th class="data-grid-th">
                <span class="data-grid-cell-content"><?= __('Selected Option') ?></span>
            </th>
            <th class="data-grid-th">
                <span class="data-grid-cell-content"><?= __('Quantity') ?></span>
            </th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getProducts($subscription->getCode()) as $product): ?>
                <tr class="data-row">
                    <td>
                        <div class="data-grid-cell-content"><?= $product->getId(); ?></div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content"><?= $product->getName(); ?></div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?= $this->getProductOptions($product); ?>
                        </div>
                    </td>
                    <td>
                        <div class="data-grid-cell-content">
                            <?= (int) $product->getQtyInvoiced(); ?>
                        </div>
                    </td>
                </tr>

            <?php endforeach; ?>
        </tbody>
    </table>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Invoices') ?></span>
    </div>
    <table class="data-grid" data-role="grid">
        <thead>
            <tr>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" >ID</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" >Invoice Id</span>
                </th>
                <th class="data-grid-th" >
                    <span class="data-grid-cell-content" >Método de pagamento</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" >Valor</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" >Valor pago</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" >Valor cancelado</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" >Valor estornado</span>
                </th>
                <th class="data-grid-th">
                    <span class="data-grid-cell-content" >Status</span>
                </th>
                <th class="data-grid-th" >
                    <span class="data-grid-cell-content" >Boleto</span>
                </th>
                <th class="data-grid-th" >
                    <span class="data-grid-cell-content" ><?= __('Actions') ?></span>
                </th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($subscription->getCharges() as $charge):
            ?>
            <tr class="data-row" data-bind="css: {'_odd-row': $index % 2}" data-repeat-index="0">
                <td>
                    <div class="data-grid-cell-content"><?= $charge->getId(); ?></div>
                </td>
                <td class="">
                    <div class="data-grid-cell-content"><?= $charge->getMundipaggId()->getValue(); ?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><?= $charge->getPaymentMethod()->getPaymentMethod(); ?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><?= $charge->getAmount(); ?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><?= $charge->getPaidAmount(); ?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><?= $charge->getCanceledAmount(); ?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><?= $charge->getRefundedAmount(); ?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><?= $charge->getStatus()->getStatus(); ?></div>
                </td>
                <td>
                    <div class="data-grid-cell-content"> <?= $charge->getBoletoUrl(); ?> </div>
                </td>
                <td>
                    <div class="data-grid-cell-content"><a title="<?= __('Cancel') ?>" href="#" target="_blank"><?= __('Cancel') ?></a></div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</section>
