<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var Magento\Braintree\Block\Form $block */

$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none"
>
    <h1>111111111111111</h1>
</fieldset>
