<main id="anchor-content" class="page-content">
    <div class="page-main-actions">
        <div class="page-actions-placeholder"></div>
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="New Plan">
                <div class="page-actions-buttons">
                    <button id="save-button" title="Save" class="action-default primary">
                        <span>Save</span>
                    </button>
                    <button id="back" title="Back" type="button" class="action- scalable back" onclick="location.href = '#;" data-ui-id="back-button">
                        <span>Back</span>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div id="page:main-container" class="page-columns">
        <div class="admin__old">
            <div id="container" class="main-col">
                <div class="entry-edit form-inline">
                    <div class="fieldset-wrapper">
                        <div class="admin__fieldset-wrapper-content _hide">
                            <fieldset class="admin__fieldset">

                                <div class="fieldset-wrapper admin__collapsible-block-wrapper products-wrapper" data-role="collapsible" >

                                    <h1>Products</h1>
                                    <div class="select-product">
                                        <label>Select the product</label>
                                        <input type="text" class="product_search" name="product_search" id="product-search">
                                        <input type="hidden" id="product_id">
                                        <input type="hidden" id="product_image">
                                        <button type="button" class="action-basic" id="add-product" data-action="add">
                                            <span>Add Product</span>
                                        </button>
                                    </div>


                                    <div class="admin__control-table-wrapper table-products" id="table-products">
                                        <div id="info-bundle" class="info-bundle">
                                            <div class="info-bundle-header">
                                                <strong><span></span></strong>
                                            </div>
                                        </div>
                                        <table id="product-info" class="admin__dynamic-rows admin__control-table">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th>Name</th>
                                                    <th>Cicle</th>
                                                    <th>Quantity</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            </tbody>
                                        </table>
                                    </div>

                                </div>

                                <div class="admin__field">
                                    <label class="admin__field-label" for="enable">
                                        <span>Enable Product</span>
                                    </label>
                                    <div class="admin__field-control _with-tooltip">
                                        <div class="admin__field admin__field-option">
                                            <input type="checkbox" class="admin__control-checkbox" name="plan[enabled]" checked id="enable">
                                            <label class="admin__field-label" for="enable"></label>
                                        </div>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label class="admin__field-label">
                                        <span>Payment Methods</span>
                                    </label>
                                    <div class="admin__field-control _with-tooltip">
                                        <div class="admin__field admin__field-option">
                                            <input type="checkbox" class="admin__control-checkbox" name="plan[payment_methods][credit_card]" id="credit-card">
                                            <label class="admin__field-label" for="credit-card">Credit Card</label>
                                        </div>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label class="admin__field-label">
                                        <span> </span>
                                    </label>
                                    <div class="admin__field-control">
                                        <div class="admin__field admin__field-option">
                                            <input type="checkbox" class="admin__control-checkbox" name="plan[payment_methods][boleto]" id="boleto">
                                            <label class="admin__field-label" for="boleto">Boleto</label>
                                        </div>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label class="admin__field-label">
                                        <span>Interval</span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="admin__control-select" name="plan[interval]">
                                            <option data-title="Week" value="W">Week</option>
                                            <option data-title="Month" value="M">Month</option>
                                            <option data-title="Year" value="Y">Year</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field">
                                    <label class="admin__field-label">
                                        <span>Interval Count</span>
                                    </label>
                                    <div class="admin__field-control">
                                        <select class="admin__control-select" name="plan[interval_count]">
                                            <?php for($i = 1;$i <= 12; $i++):?>
                                            <option value="<?php echo $i?>"><?php echo $i?></option>
                                            <?php endfor;?>
                                        </select>
                                    </div>
                                </div>

                                <div class="admin__field admin__field-small _required">
                                    <label class="admin__field-label">
                                        <span>Trial Days</span>
                                    </label>
                                    <div class="admin__field-control">
                                        <input class="admin__control-text" type="text" name="plan[trial_period_days]" id="" maxlength="255">
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script>

    require([
        'jquery',
        'jquery/ui'
    ], function ($) {
        'use strict';

        $(document).ready(function(){

            var products = Object.values(<?php echo $block->getBundleProducts();?>);

            $("#product-search").autocomplete({
                minLength:3,
                source: products,
                select: function( event, ui ) {
                    $("#product_id").val(ui.item.id);
                    $("#product_image").val(ui.item.image);
                    $("#info-bundle span").html(ui.item.value);
                },
                search: function(event, oUi) {
                    var currentValue = $(event.target).val().toLowerCase();
                    var arraySearch = [];
                    for (var index in products) {

                        var productName = products[index].value.toLowerCase();

                        if (productName.indexOf(currentValue) >= 0) {
                            arraySearch.push(products[index]);
                        }
                    }
                    $(this).autocomplete('option', 'source', arraySearch);
                }
            });


            $("#add-product").on('click', function() {
                var data = {
                    productId: $(this).parent().find("#product_id").val()
                }

                $(this).attr('disabled', true);

                if ($(this).data('action') == 'add') {
                    var url = "<?php echo $block->getUrl('*/plans/searchproduct');?>";
                    $.getJSON(url, data, success);
                    return;
                }

                $("#table-products").hide();
                $("#table-products tbody").empty();
                $("#product-search").val("");
                changeButton();
                return;
            })

            function success(data) {
                $("#table-products").show();
                fillTable(data);
                changeButton();
            }

            function fillTable(data) {
                for (var index in data) {
                    addRow(data[index], index);
                }
            }

            function addRow(data, index) {

                var tr = $('<tr>').append(
                    $('<td>').html("<img src='" + data.image + "' width='70px' height='70px'>"),
                    $('<td>').text(data.name),
                    $('<td>').html("<input type='number' name='plan[itens][" + index +"][cicle]' step='1' min='0'/>"),
                    $('<td>').html("<input type='number' name='plan[itens][" + index +"][quantity]' step='1' min='1'/>"),
                );

                var table = $('#table-products tbody');
                table.append(tr);
            }

            function changeButton(){
                var button = $("#add-product");
                button.attr('disabled', false);

                if (button.data('action') == 'add') {
                    $('#product-search').attr('disabled', true);
                    button.data('action', 'remove');
                    button.find('span').html("Remove Product");
                    return;
                }
                $('#product-search').attr('disabled', false);
                button.data('action', 'add');
                button.find('span').html("Add Product");
                return;
            }

        });

    });



</script>