<?php
/**
 * @var $block Kyc
 */

use Pagarme\Pagarme\Block\Customer\Marketplace\Kyc;

$recipientId = $block->getRecipient()->getId();

if (empty($recipientId)) {
    return;
}

?>

<div class="wk-mp-design">
    <div class="mp-widgets pagarme-kyc">
        <div class="container">
            <div class="pagarme-kyc-box">
                <div class="pagarme-kyc-box-title">
                    <div class="p-5"><?= __('Pagar.me Recipient') ?></div>
                </div>
                <div class="pagarme-kyc-box-content">
                    <div class="p-5">
                        <p><?= __('You can now sell, but you must successfully complete our <b>security '
                                . 'validation</b> to release your sales amounts.') ?></p>
                        <button class="button" id="pagarme-kyc-start-validation">
                            <span><?= __('Start validation') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="modal-content">
    <div class="modal-inner-content pagarme-kyc-modal">
        <p><?= __('Point the smartphone camera to read the QRCode.') ?></p>
        <p><img src="" alt="QRCode" id="pagarme-kyc-qrcode" /></p>
        <p><?= sprintf(__('Or use this %slink%s.'), '<a id="pagarme-kyc-link" target="_blank" rel="noreferrer">', '</a>') ?></p>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#pagarme-kyc-start-validation": {
            "kyc": {"id": "<?= $recipientId ?>"}
        }
    }
</script>
