<?php
/**
 * Class billet
 *
 * @author      MundiPagg Embeddables Team <embeddables@mundipagg.com>
 * @copyright   2017 MundiPagg (http://www.mundipagg.com)
 * @license     http://www.mundipagg.com Copyright
 *
 * @link        http://www.mundipagg.com
 */
?>
<?php

/* @var MundiPagg\MundiPagg\Block\Payment\Info\Billet $this */
$this;

/**
 * @var \Mundipagg\Core\Kernel\Aggregates\Transaction $lastTransaction
 */
$lastTransaction = $this->getInfoTransactions();
$postData = (json_decode($lastTransaction->getPostData()->tran_data, true));
?>

<?php if($postData !== null && isset($postData['nosso_numero'])) { ?>
    <span>
        <b><?= __('Our Number'); ?>: </b><?= $postData['nosso_numero'] ?>
    </span>
    <br/>
    <br/>
<?php } ?>

<?php if ($this->getBilletUrl() && $this->getInfo()->getOrder()->getStatus() == 'pending'): ?>
    <span><?php echo __($this->getTitle()) ?></span>
    <hr/>
    <a class="action tocart primary" href="<?php echo $this->getBilletUrl() ?>"
       target="_blank"><?php echo __('Print Billet') ?></a>
<?php else: ?>
    <span><?php echo __($this->getTitle()) ?></span>
<?php endif ?>

<?php
$this->getInfoTransactions();
?>
