<?php
    /**
     * @var \Pagarme\Core\Kernel\Aggregates\Transaction $info
     */
    $info =  $this->getTransactionInfo();
?>
<span>
    <?= __($this->getTitle()); ?>
</span>
<br /><br />
<span>
    <b><?= __('Brand'); ?>: </b>
    <?= $info['cardBrand'] ?>
</span><br />
<span>
    <b><?= __('Number'); ?>: </b>
    <?= $info['lastFour']; ?>
</span>
<br />
<?php if (!empty($info['installments'])) : ?>
    <span>
        <b><?= __('Installments'); ?>: </b>
        <?= $info['installments'] ?>
    </span>
<?php endif; ?>
<?php if (!empty($info['authorized'])) : ?>
    <br />
    <span>
        <b><?= __('NSU'); ?>: </b>
        <?= $info['authorized']; ?>
    </span>
<?php endif; ?>
<br />
<?php if (!empty($info['captured'])) : ?>
    <br />
    <span><b><?= __('NSU from capture'); ?>: </b><?= $info['captured']; ?></span>
<?php endif; ?>
<?php if (!empty($info['tid'])) : ?>
    <br />
    <span>
        <b><?= __('TID'); ?>: </b>
        <?= $info['tid']; ?>
    </span>
<?php endif; ?>
<?php if (!empty($info['3dsStatus'])) : ?>
    <br />
    <span>
        <b><?= __('3DS Status'); ?>: </b>
        <?= __($info['3dsStatus']); ?>
    </span>
<?php endif; ?>
<br />
<span><?= $info['acquirerMessage']; ?></span>