<?php /* @var \MundiPagg\MundiPagg\Block\Payment\Info\CreditCard $this */ $this; ?>
<?php if ($this->getCcType()): ?>

    <?php
    /**
     * @var \Mundipagg\Core\Kernel\Aggregates\Transaction $lastTransaction
     */
    $lastTransaction =  $this->getInfoTransactions();
    ?>
    <span><?php echo __($this->getTitle()); ?></span>
    <br/>
    <br/>
    <span><b><?php echo __('Brand'); ?>: </b><?php echo $this->getCcBrand(); ?></span>
    <br/>
    <span><b><?php echo __('Number'); ?>: </b><?php echo $this->getCardLast4(); ?></span>
    <br/>
    <span><b><?php echo __('Installments'); ?>: </b><?php echo $this->getInstallments(); ?></span>
    <br/>
    <span><b><?= __('NSU'); ?>: </b><?= $lastTransaction->getAcquirerNsu() ?></span>
    <br/>
    <span><b><?= __('TID'); ?>: </b><?= $lastTransaction->getAcquirerTid() ?></span>
<?php endif ?>
