<?php /* @var \Pagarme\Pagarme\Block\Payment\Info\CreditCard $this */ ?>
<?php if ($this->getCcType()): ?>

    <?php
    /**
     * @var \Pagarme\Core\Kernel\Aggregates\Transaction $lastTransaction
     */
    $lastTransaction =  $this->getTransactionInfo();
    $threeDSStatus =  $this->getThreeDSStatus();
    ?>
    <span><?= __($this->getTitle()); ?></span>
    <br/>
    <br/>
    <span><b><?= __('Brand'); ?>: </b><?= $this->getCcBrand(); ?></span>
    <br/>
    <span><b><?= __('Number'); ?>: </b><?= $this->getCardLast4(); ?></span>
    <br/>
    <span><b><?= __('Installments'); ?>: </b><?= $this->getInstallments(); ?></span>
    <?php if (!empty($lastTransaction['authorized'])): ?>
        <br/>
        <span><b><?= __('NSU'); ?>: </b><?= $lastTransaction['authorized']; ?></span>
    <?php endif; ?>
    <br/>
    <?php if (!empty($lastTransaction['captured'])): ?>
        <br/>
        <span><b><?= __('NSU from capture'); ?>: </b><?= $lastTransaction['captured']; ?></span>
    <?php endif; ?>
    <?php if (!empty($lastTransaction['tid'])): ?>
        <br/>
        <span><b><?= __('TID'); ?>: </b><?= $lastTransaction['tid']; ?></span>
    <?php endif; ?>
    <?php if (!empty($threeDSStatus)): ?>
        <br/>
        <span><b><?= __('3DS Status'); ?>: </b><?= __($threeDSStatus); ?></span>
    <?php endif; ?>
<?php endif ?>
