<?php

use Pagarme\Core\Kernel\Aggregates\Transaction;
use Pagarme\Pagarme\Block\Payment\Info\Pix;

$postData = [];

/* @var Pix $this */

/**
 * @var Transaction $lastTransaction
 */
$lastTransaction = $this->getTransactionInfo();
if (!empty($lastTransaction)) {
    $postData = (json_decode($lastTransaction->getPostData()->tran_data, true));
}
?>

<?php if ($postData !== null && isset($postData['nosso_numero'])) { ?>
    <span>
        <b><?= __('Our Number'); ?>: </b><?= $postData['nosso_numero'] ?>
    </span>
    <br/>
<?php } ?>

<?php if ($postData !== null && isset($postData['document_number'])) { ?>
    <span>
        <b><?= __('Document Number'); ?>: </b><?= $postData['document_number'] ?>
    </span>
    <br/>
    <br/>
<?php } ?>

<?php if ($this->getPixUrl() && $this->getInfo()->getOrder()->getStatus() == 'pending'): ?>
    <span><?php echo __($this->getTitle()) ?></span>
    <hr/>
    <a class="action tocart primary" href="<?php echo $this->getPixUrl() ?>"
       target="_blank"><?php echo __('Print QrCode') ?></a>
<?php else: ?>
    <span><?php echo __($this->getTitle()) ?></span>
<?php endif ?>

