<?php
/**
 * Class billet
 *
 * @author      MundiPagg Embeddables Team <embeddables@mundipagg.com>
 * @copyright   2017 MundiPagg (http://www.mundipagg.com)
 * @license     http://www.mundipagg.com Copyright
 *
 * @link        http://www.mundipagg.com
 */

?>

<?php
/**
 * @var \Mundipagg\Core\Kernel\Aggregates\Transaction $lastTransaction
 */
$lastTransactions =  $this->getInfoTransactions();
?>
<?php if ($this->getCcTypeFirst() && $this->getCcTypeSecond()): ?>
    <span><?php echo __($this->getTitle()); ?></span>
    <br/>
    <br/>
    <span style="font-size: initial;"><b><?php echo __('First Card'); ?></b></span>
    <br/>
    <span><b><?php echo __('Brand'); ?>: </b><?php echo $this->getCcTypeFirst(); ?></span>
    <br/>
    <span><b><?php echo __('Number'); ?>: </b><?php echo $this->getFirstCardLast4(); ?></span>
    <br/>
    <span><b><?php echo __('Installments'); ?>: </b><?php echo $this->getInstallmentsFirstCard(); ?></span>
    <br/>
    <span><b><?php echo __('Amount'); ?>: </b><?php echo $this->getFirstCardAmount(); ?></span>
    <br/>
    <span><b><?= __('NSU'); ?>: </b><?= $lastTransactions['card1']->getAcquirerNsu() ?></span>
    <br/>
    <span><b><?= __('TID'); ?>: </b><?= $lastTransactions['card1']->getAcquirerTid() ?></span>
    <br/>
    <br/>
    <span style="font-size: initial;"><b><?php echo __('Second Card'); ?></b></span>
    <br/>
    <span><b><?php echo __('Brand'); ?>: </b><?php echo $this->getCcTypeSecond(); ?></span>
    <br/>
    <span><b><?php echo __('Number'); ?>: </b><?php echo $this->getSecondCardLast4(); ?></span>
    <br/>
    <span><b><?php echo __('Installments'); ?>: </b><?php echo $this->getInstallmentsSecondCard(); ?></span>
    <br/>
    <span><b><?php echo __('Amount'); ?>: </b><?php echo $this->getSecondCardAmount(); ?></span>
    <br/>
    <span><b><?= __('NSU'); ?>: </b><?= $lastTransactions['card2']->getAcquirerNsu() ?></span>
    <br/>
    <span><b><?= __('TID'); ?>: </b><?= $lastTransactions['card2']->getAcquirerTid() ?></span>
    <br/>

<?php endif ?>
