<?php
/**
 * Class TwoCreditCard
 *
 * @author      Open Source Team
 * @copyright   2021 Pagar.me (https://pagar.me)
 * @license     https://pagar.me Copyright
 *
 * @link        https://pagar.me
 */

?>
<?php
/* @var \Pagarme\Pagarme\Block\Payment\Info\CreditCard $this */;
/**
 * @var \Pagarme\Core\Kernel\Aggregates\Transaction $lastTransaction
 */
$lastTransactions =  $this->getTransactionInfo();
?>
<?php if ($this->getCcTypeFirst() && $this->getCcTypeSecond()): ?>
    <span><?php echo __($this->getTitle()); ?></span>
    <br/>
    <br/>
    <span style="font-size: initial;"><b><?php echo __('First Card'); ?></b></span>
    <br/>
    <span><b><?php echo __('Brand'); ?>: </b><?php echo $this->getCcTypeFirst(); ?></span>
    <br/>
    <span><b><?php echo __('Number'); ?>: </b><?php echo $this->getFirstCardLast4(); ?></span>
    <br/>
    <span><b><?php echo __('Installments'); ?>: </b><?php echo $this->getInstallmentsFirstCard(); ?></span>
    <br/>
    <span><b><?php echo __('Amount'); ?>: </b><?php echo $this->getFirstCardAmount(); ?></span>

    <?php if (!empty($lastTransactions['card1']['authorized'])) { ?>
        <br/>
        <span><b><?= __('NSU'); ?>: </b><?= $lastTransactions['card1']['authorized'] ?></span>
        <br/>
    <?php } ?>

    <?php if (!empty($lastTransactions['card1']['captured'])) { ?>
        <br/>
        <span><b><?= __('NSU from capture'); ?>: </b><?= $lastTransactions['card1']['captured'] ?></span>
        <br/>
    <?php } ?>

    <?php if (!empty($lastTransactions['card1']['tid'])) { ?>
        <span><b><?= __('TID'); ?>: </b><?= $lastTransactions['card1']['tid'] ?></span>
    <?php } ?>

    <br/>
    <br/>
    <span style="font-size: initial;"><b><?php echo __('Second Card'); ?></b></span>
    <br/>
    <span><b><?php echo __('Brand'); ?>: </b><?php echo $this->getCcTypeSecond(); ?></span>
    <br/>
    <span><b><?php echo __('Number'); ?>: </b><?php echo $this->getSecondCardLast4(); ?></span>
    <br/>
    <span><b><?php echo __('Installments'); ?>: </b><?php echo $this->getInstallmentsSecondCard(); ?></span>
    <br/>
    <span><b><?php echo __('Amount'); ?>: </b><?php echo $this->getSecondCardAmount(); ?></span>

    <?php if (!empty($lastTransactions['card2']['authorized'])) {?>
        <br/>
        <span><b><?= __('NSU'); ?>: </b><?= $lastTransactions['card2']['authorized'] ?></span>
        <br/>
    <?php } ?>

    <?php if (!empty($lastTransactions['card2']['captured'])) {?>
        <br/>
        <span><b><?= __('NSU from capture'); ?>: </b><?= $lastTransactions['card2']['captured'] ?></span>
        <br/>
    <?php } ?>

    <?php if (!empty($lastTransactions['card2']['tid'])) {?>
        <span><b><?= __('TID'); ?>: </b><?= $lastTransactions['card2']['tid'] ?></span>
        <br/>
    <?php } ?>

<?php endif ?>
