name: CD – Build & Deploy magento2-pagarme

on:
  push:
    branches: [master, stg, develop]
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: magento2-pagarme
  IMAGE_TAG: php8

jobs:

  build-and-push:
    name: Build & push to ACR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      full_tag: ${{ steps.tag.outputs.full_tag }}

    steps:
      - uses: actions/checkout@v4


      - name: Create auth.json from secrets
        run: |
          cat > auth.json <<EOF
          {
            "http-basic": {
              "repo.magento.com": {
                "username": "${{ secrets.MAGENTO_REPO_PUBLIC_KEY }}",
                "password": "${{ secrets.MAGENTO_REPO_PRIVATE_KEY }}"
              }
            }
          }
          EOF

      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_ACCOUNT }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ secrets.DOCKER_ACCOUNT }}/magento2-pagarme:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_ACCOUNT }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_ACCOUNT }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          secret-files: |
            composer_auth=./auth.json
