name: CD Master

on:
  pull_request:
    branches: ["master"]
    types: closed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
jobs:
  call-workflow-cd:
    uses: pagarme/magento2/.github/workflows/cd_reusable.yml@master
    with:
      matrix_tags: "['master']"
    secrets:
      inherit