name: CD REUSABLE

on:
  workflow_call:
    inputs:
      matrix_tags:
        required: true
        type: string

jobs:
  publish:
    strategy:
      matrix:
        tags: ${{ fromJson(  inputs.matrix_tags ) }} 
    name: Publish
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Code
      uses: actions/checkout@v3
    -
      name: Copy CI files to root
      run: |
        cp .github/data/${{ matrix.tags }}/Dockerfile .
    -
      name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ secrets.DOCKER_ACCOUNT }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_ACCOUNT }}/magento2-pagarme
    -
      name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        build-args: |
          MAGENTO_KEY=${{ secrets.MAGENTO_KEY }}
          MAGENTO_SECRET=${{ secrets.MAGENTO_SECRET }}
          MARKETPLACE_KEY=${{ secrets.MARKETPLACE_KEY }}
          MARKETPLACE_SECRET=${{ secrets.MARKETPLACE_SECRET }}
          MARKETPLACE_REPO=${{ secrets.MARKETPLACE_REPO }}
          MARKETPLACE_NAME=${{ secrets.MARKETPLACE_NAME }}
          MARKETPLACE_VERSION=${{ secrets.MARKETPLACE_VERSION }}
          MARKETPLACE_REPO_URL=${{ secrets.MARKETPLACE_REPO_URL }}
        context: .
        push: true
        tags: ${{ secrets.DOCKER_ACCOUNT }}/magento2-pagarme:${{ matrix.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    # name: Commit and push Docker image
    # run: |
    #   sleep 5 && docker stop magento2_bitnami
    #   docker login ${{ secrets.DOCKER_ACCOUNT }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #   docker commit magento2_bitnami "magento2-pagarme:${{ github.ref_name }}"
    #   docker push "magento2-pagarme:${{ github.ref_name }}"
    # name: Send deployment webhook to Rancher
    # run: |
    #   BODY='{"push_data":{"tag":"'"${{ github.ref }}"'"},"repository":{"repo_name":"'"${{ secrets.DOCKER_ACCOUNT }}/${{ github.repository }}"'"}}'
    #   curl -X POST ${{ secrets.RANCHER_STG_DEPLOY_URL }} -H 'Content-Type: application/json' -d "${BODY}"